language: node_js
node_js:
  - 7
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
